server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallet/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: cGF5emFwcC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLWhzMjU2
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans