server:
  port: 8082

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: cGF5emFwcC1zZWNyZXQta2V5LXRoYXQtaXMtbG9uZy1lbm91Z2gtZm9yLWhzMjU2
  expiration: 86400000

